config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'application#index'
  resources :authors
  resources :books
  resources :users
  resources :favourite_book_users
  resources :stores
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/models/favourite_book_user.rb
class FavouriteBookUser < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/store.rb
class Store < ApplicationRecord
  geocoded_by :full_address
  after_validation :geocode
  
  def full_address
    "#{address}, #{city}, #{state}, #{postcode}, #{country}"
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def index
    @favourites = FavouriteBookUser.where(user_id: current_user)
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_user!
  def index
    @authors = Author.all
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def index
    @books = Book.order(rating: :desc)
  end

  def show
    @book = Book.find(params[:id])
    if @book.counter == nil
      @book.counter = 1
    else
    @book.counter +=1
  end
    @book.save
  end
end

app/controllers/favourite_book_users_controller.rb
class FavouriteBookUsersController < ApplicationController
  def show
    @user = current_user
    @favourites = FavouriteBookUser.where(user_id: current_user)
  end

  def new
    @new_favourite = FavouriteBookUser.new
    @new_favourite.user_id = current_user.id
    @new_favourite.book_id = Book.find(params[:book_id])
    @new_favourite.save
    redirect_to :back
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
    @stores = Store.all
  end
  def show
    @store = Store.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  @user = current_user
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/application/index.html.erb
<% @title="Amazon - Books Books Books" %>

<img src= "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Amazon_logo.jpg/1200px-Amazon_logo.jpg" style="width:100vw">

app/views/authors/index.html.erb
<% @title="Amazon - Books Books Books" %>
<h1> Authors </h1>
<% @authors.each do |author| %>
<h2> <%= author.name %> </h2>
<ul>
  <% author.books.each do |book| %>
  <li> <%= book.title%>  </li>
  <% end %>
</ul>
<%end%>

app/views/books/index.html.erb
<% @title="Amazon - Books Books Books" %>
<h1> BOOKS </h1>
<% @books.each do |book| %>
<h2><%= book.title %>
<% book.rating.times do %>
 *
 <% end %> </h2>
<h3>By <%= book.author.name %> </h3>
<h4> <%= link_to "View More..", book %> </h4>
<br>
<% end %>

app/views/books/show.html.erb
<% @title="Amazon - #{@book.title}"%>
<div class = "container">
  <div class = "container">
  <h1> <%= @book.title %>
    <% @book.rating.times do %>
     *
    <% end %> </h1>
  <h3> By <%= @book.author.name %> </h3>
  </div>
  <%= image_tag @book.image_url, :alt => 'Picture of Book', class: "book-pic" %>
  <p>
    <%= link_to "Add to favourites", new_favourite_book_user_path %>
  </p>
  <p> This book has been viewed <%= @book.counter %> times. </p>
</div>

app/views/favourite_book_users/show.html.erb
<h1> <%= @user.email %>'s favourite books </h1>
<% @favourites.each do |favourites| %>
  <h2> <%= favourites.book.title %> </h2>
  <h3> By <%= favourites.book.author.name %> </h3>
  <h4> <%= link_to "View More..", favourites.book %> </h4>
  <br>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <title><%= @title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <%= link_to "Amazon", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Stores", stores_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Authors", authors_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Books", books_path, class: "nav-link" %>
          </li>
          <% if current_user %>
          <li class="nav-item">
            <%= link_to "Favourites (#{FavouriteBookUser.where(user_id: current_user).count})", favourite_book_user_path(current_user.id), class: "nav-link" %>
          </li><% end %>
        </ul>
      </div>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Profile", user_path(current_user.id), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, class: "nav-link" %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Signup", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <%= yield %>
  </body>
</html>

app/views/stores/index.html.erb
<h1> Brick & Mortar Stores </h1>
<% @stores.each do |store| %>
 <h2><%= link_to store.title, store %> </h2>
 <h3> <%= store.full_address %> </h3>
 <br>
 <% end %>

app/views/stores/show.html.erb
<h1> <%= @store.title %> </h1>
<h2> <%= @store.full_address %> </h2>
<iframe
  width="600"
  height="450"
  frameborder="0"
  style="border:0"
  src="https://www.google.com/maps/embed/v1/streetview?key=AIzaSyCBlAodTRLQOt9XqI1d0GZ-RqCYOLq2414&location=<%=@store.latitude%>,<%=@store.longitude%>&heading=210&pitch=10&fov=35">
  </iframe>

app/views/users/show.html.erb
<h1> Welcome, <%= @user.email %> </h1>